Palindrome_-Checke
Marwa-Sadat/-Palindrome_-Checker pull request #1
Opened 2024-06-28 12:57 UTC by Marwa-Sadat

*Palindrome Checker*: 🪞✨ A simple tool that checks if a word, phrase, or sequence reads the same backward as forward. 🔁📝 It removes spaces and punctuation, ensuring an accurate check. 🔍✅ Perfect for linguistics enthusiasts, puzzle lovers, and anyone curious about symmetrical sequences! 🧩❤ Enhance your understanding of palindromes with ease and efficiency. 📚💡
![Screenshot 2024-06-26 195426](https://github.com/Marwa-Sadat/-Palindrome_-Checker/assets/168111110/1b8ec5ec-4614-4dd4-8b71-8e51956e0571)

2024-07-01 05:50 UTC, zainabbehzad requested changes
Hi @Marwa-Sadat
Excellent work You have done a great job implementing the project requirements.

✔Great design implemented.
✔Created a professional Repo.
✔Correct use of Gitflow.
✔Commit messages are meaningful.
✔Setup the linters correctly.
✔No linters errors.
✔You have followed and completed the Palindrome Checker and all requirements.
✔Created the pull request (From your  Palindrome-checker branch to the development branch you created a pull request and submitted the pull request link for review).
✔Good PR description.
✔Your repo has a professional README.md.
✔Your project design is responsive.
🧩Your code is clean.
  On index.html
* Your body spacing is not aligned correctly:
* All child elements should be two spaces ahead of their parent elements.

2024-07-01 06:19 UTC, ahzamir commented
@Marwa-Sadat 

- You have to implement your partner's feedback and get their approval, then ask for a review from me.

2024-07-01 19:36 UTC, zainabbehzad approved these changes
Hi @Marwa-Sadat
Excellent work You have done a great job implementing the project requirements.

✔Great design implemented.
✔Created a professional Repo.
✔Correct use of Gitflow.
✔Commit messages are meaningful.
✔Setup the linters correctly.
✔No linters errors.
✔You have followed and completed the Palindrome Checker and all requirements.
✔Your codes passes all FreeCodeCamp requiremenrs.
✔Created the pull request (From your  Palindrome-checker branch to the development branch you created a pull request and submitted the pull request link for review).
✔Good PR description.
✔Your repo has a professional README.md.
✔Your project design is responsive.
✔Your code is clean.

2024-07-01 20:03 UTC, Marwa-Sadat commented
@ahzamir Hi sir hope you are well, please check my project .

2024-07-02 10:18 UTC, ahzamir requested changes
@Marwa-Sadat 

- Well done marwa, you have done a great job implementing lots of requirements and creating such a well-designed project but your README.md file needs some changes inorder to get the final approval check the comments below for more details:

![image](https://github.com/Marwa-Sadat/-Palindrome_-Checker/assets/96838030/5bc552f5-a1ba-421c-ace4-520cd1c2136a)

- And don't forget to deploy your project

2024-07-02 10:18 UTC, ahzamir commented on README.md
> +markdown
Remove these 3 lines

2024-07-02 10:18 UTC, ahzamir commented on README.md
> +- [Your Programming Language] installed on your machine.
- This is fine but it is like a template add your programming language here for example `[NodeJS] Installed on your machine.

2024-07-02 10:18 UTC, ahzamir commented on README.md
> +    git clone https://github.com/yourusername/palindrome-checker.git
- Here add your project SSH link for now it is like an example

2024-07-02 10:18 UTC, ahzamir commented on README.md
> +    Or, if there are no dependencies, you can skip this step.
Remove these template examples as you don't have dependencies on your project.

2024-07-02 10:18 UTC, ahzamir commented on README.md
> +    python palindrome_checker.py
- Remove these 2 lines instead add `Open Index.html from root folder`

2024-07-02 10:18 UTC, ahzamir commented on README.md
> +
- Remove this as you don't use python

2024-07-02 10:18 UTC, ahzamir commented on README.md
> +
- Remove this example as this is for python and you used JS

2024-07-02 10:18 UTC, ahzamir commented on README.md
> +![Demo](https://private-user-images.githubusercontent.com/168111110/344379010-90dc49e6-f19b-4c93-8fab-c1822c441425.png?)
- Add your own demo (Screenshot or Live deployed link)

2024-07-02 10:18 UTC, ahzamir commented on README.md
> +    git clone https://github.com/yourusername/palindrome-checker.git
- Add you SSH link here

2024-07-02 10:18 UTC, ahzamir commented on README.md
> +    git checkout -b feature/your-feature-name
- Update this with your own feature branch name

2024-07-04 16:05 UTC, Marwa-Sadat commented
@ahzamir Hi sir I hope you are well, I have done all the feedback, please check my project.

2024-07-04 16:17 UTC, ahzamir approved these changes
### Hi @Marwa-Sadat 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/Marwa-Sadat/-Palindrome_-Checker/assets/96838030/d2f0d340-92da-4866-b468-afa1a0584032)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-07-04 16:41 UTC, Marwa-Sadat commented
@ahzamir thank you so much sir😊🙂

2024-07-05 14:32 UTC, ahzamir commented
> @ahzamir thank you so much sir😊🙂

- You're welcome

2024-07-08 07:02 UTC, merged